version: '3.9'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: hortitech-backend
    ports:
      - "4000:4000"
    env_file:
      - ./backend/.env
    environment:
      NODE_ENV: production
      FRONTEND_URL: http://localhost:3000
    networks:
      - hortitech-net
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: hortitech-frontend
    ports:
      - "3000:3000"
    env_file:
      - ./frontend/.env.local
    environment:
      NODE_ENV: production
      NEXT_PUBLIC_BACKEND_URL: http://localhost:4000/api
    depends_on:
      - backend
    networks:
      - hortitech-net
    restart: unless-stopped

networks:
  hortitech-net:
    driver: bridge